<?php
return array(
	'higher education'=>array(
		'en'=>'higher education',
		''=>'',
		'es'=>'Educación superior',
		'el'=>'τριτοβάθμιας εκπαίδευσης',
		'it'=>'istruzione superiore',
		'fr'=>'enseignement supérieur',
		'tr'=>'yüksek öğrenim',
	),
	'vocational education'=>array(
		'en'=>'vocational education',
		''=>'',
		'es'=>'Educación vocacional',
		'el'=>'επαγγελματικής εκπαίδευσης',
		'it'=>'formazione professionale',
		'fr'=>'enseignement professionnel',
		'tr'=>'mesleki eğitim',
	),
	'compulsory education'=>array(
		'en'=>'compulsory education',
		''=>'',
		'es'=>'educación obligatoria',
		'el'=>'υποχρεωτικής εκπαίδευσης',
		'it'=>'istruzione obbligatoria',
		'fr'=>'enseignement obligatoire',
		'tr'=>'zorunlu eğitim',
	),
	'continuing education'=>array(
		'en'=>'continuing education',
		''=>'',
		'es'=>'educación continua',
		'el'=>'συνεχιζόμενη εκπαίδευση',
		'it'=>'formazione continua',
		'fr'=>'formation continue',
		'tr'=>'sürekli eğitim',
	),
	'distance education'=>array(
		'en'=>'distance education',
		''=>'',
		'es'=>'Educación a distancia',
		'el'=>'εξ αποστάσεως εκπαίδευση',
		'it'=>'formazione a distanza',
		'fr'=>'enseignement à distance',
		'tr'=>'Uzaktan eğitim',
	),
	'professional development'=>array(
		'en'=>'professional development',
		''=>'',
		'es'=>'desarrollo profesional',
		'el'=>'επαγγελματική εξέλιξη',
		'it'=>'sviluppo professionale',
		'fr'=>'perfectionnement professionnel',
		'tr'=>'mesleki gelişim',
	),
	'policy making'=>array(
		'en'=>'policy making',
		''=>'',
		'es'=>'formulación de políticas',
		'el'=>'χάραξη πολιτικής',
		'it'=>'elaborazione di politiche',
		'fr'=>'élaboration de la politique',
		'tr'=>'politika yapma',
	),
	'pre-school'=>array(
		'en'=>'pre-school',
		''=>'',
		'es'=>'preescolar',
		'el'=>'Νηπιαγωγείο',
		'it'=>'pre-scuola',
		'fr'=>'Pre-School',
		'tr'=>'okul öncesi',
	),
	'special education'=>array(
		'en'=>'special education',
		''=>'',
		'es'=>'Educación especial',
		'el'=>'ειδικής αγωγής',
		'it'=>'educazione speciale',
		'fr'=>'éducation spéciale',
		'tr'=>'özel eğitim',
	),
	'other'=>array(
		'en'=>'other',
		''=>'',
		'es'=>'otros',
		'el'=>'άλλα',
		'it'=>'altri',
		'fr'=>'autres',
		'tr'=>'diğer',
	),
	'fr'=>array(
		'en'=>'French',
		''=>'',
		'es'=>'Francés',
		'el'=>'Γαλλικά',
		'it'=>'Francese',
		'fr'=>'Français',
		'tr'=>'Fransızca',
	),
	'en'=>array(
		'en'=>'English',
		''=>'',
		'es'=>'Inglés',
		'el'=>'Αγγλικά',
		'it'=>'Inglese',
		'fr'=>'Anglais',
		'tr'=>'İngilizce',
	),
	'de'=>array(
		'en'=>'German',
		''=>'',
		'es'=>'Alemán',
		'el'=>'Γερμανικά',
		'it'=>'Tedesco',
		'fr'=>'Allemand',
		'tr'=>'Almanca',
	),
	'or'=>array(
		'en'=>'Oriya',
		''=>'',
		'es'=>'Oriya',
		'el'=>'Οριγικό',
		'it'=>'Oriya',
		'fr'=>'Oriya',
		'tr'=>'Oriya dili',
	),
	'hi'=>array(
		'en'=>'Hindi',
		''=>'',
		'es'=>'Hindi',
		'el'=>'Χίντι',
		'it'=>'Hindi',
		'fr'=>'Hindi',
		'tr'=>'Hintçe',
	),
	'el'=>array(
		'en'=>'Greek',
		''=>'',
		'es'=>'Griego',
		'el'=>'Ελληνικά',
		'it'=>'Greco',
		'fr'=>'Grec',
		'tr'=>'Yunanca',
	),
	'es'=>array(
		'en'=>'Spanish',
		''=>'',
		'es'=>'Español',
		'el'=>'Ισπανικά',
		'it'=>'Spagnolo',
		'fr'=>'Espagnol',
		'tr'=>'İspanyolca',
	),
	'kn'=>array(
		'en'=>'Kannada',
		''=>'',
		'es'=>'Kannada',
		'el'=>'Κανάντα',
		'it'=>'Kannada',
		'fr'=>'Canara',
		'tr'=>'Kannada dili',
	),
	'pt'=>array(
		'en'=>'Portuguese',
		''=>'',
		'es'=>'Portugués',
		'el'=>'Πορτογαλικά',
		'it'=>'Portoghese',
		'fr'=>'Portugais',
		'tr'=>'Portekizce',
	),
	'hu'=>array(
		'en'=>'Hungarian',
		''=>'',
		'es'=>'Húngaro',
		'el'=>'Ουγγρικά',
		'it'=>'Ungherese',
		'fr'=>'Hongrois',
		'tr'=>'Macarca',
	),
	'et'=>array(
		'en'=>'Estonian',
		''=>'',
		'es'=>'Estonio',
		'el'=>'Εσθονικά',
		'it'=>'Estone',
		'fr'=>'Estonien',
		'tr'=>'Estonca',
	),
	'application/pdf'=>array(
		'en'=>'application/pdf',
		''=>'',
		'es'=>'Application/pdf',
		'el'=>'εφαρμογή/pdf',
		'it'=>'application/pdf',
		'fr'=>'application/pdf',
		'tr'=>'uygulama/pdf',
	),
	'text/html'=>array(
		'en'=>'text/html',
		''=>'',
		'es'=>'texto/html',
		'el'=>'κείμενο/html',
		'it'=>'testo/html',
		'fr'=>'texte/html',
		'tr'=>'metin/html',
	),
	'image/jpeg'=>array(
		'en'=>'image/jpeg',
		''=>'',
		'es'=>'image/jpeg',
		'el'=>'εικόνα/jpeg',
		'it'=>'immagine jpeg',
		'fr'=>'image/jpeg',
		'tr'=>'görüntü/jpeg',
	),
	'application/vnd.ms-powerpoint'=>array(
		'en'=>'application/vnd.ms-powerpoint',
		''=>'',
		'es'=>'aplicación/vnd.ms-powerpoint',
		'el'=>'εφαρμογή/vnd.ms-powerpoint',
		'it'=>'Application/vnd. ms-powerpoint',
		'fr'=>'application/vnd.ms-powerpoint',
		'tr'=>'uygulama/vnd.ms-powerpoint',
	),
	'application/octet-stream'=>array(
		'en'=>'application/octet-stream',
		''=>'',
		'es'=>'application/octet-stream',
		'el'=>'εφαρμογή/οκτάδα-ροή',
		'it'=>'application/octet-stream',
		'fr'=>'application/octet-stream',
		'tr'=>'Application/octet-stream',
	),
	'application/zip'=>array(
		'en'=>'application/zip',
		''=>'',
		'es'=>'application/zip',
		'el'=>'εφαρμογή/zip',
		'it'=>'Application/zip',
		'fr'=>'application/zip',
		'tr'=>'uygulama/posta kodu',
	),
	'image/gif'=>array(
		'en'=>'image/gif',
		''=>'',
		'es'=>'image/gif',
		'el'=>'εικόνα/gif',
		'it'=>'image/gif',
		'fr'=>'image/gif',
		'tr'=>'image/gif',
	),
	'text/plain'=>array(
		'en'=>'text/plain',
		''=>'',
		'es'=>'text/plain',
		'el'=>'κείμενο/απλό',
		'it'=>'text/plain',
		'fr'=>'text/plain',
		'tr'=>'metin/düz',
	),
	'video/x-ms-wmv'=>array(
		'en'=>'video/x-ms-wmv',
		''=>'',
		'es'=>'video/x-ms-wmv',
		'el'=>'βίντεο/x-ms-wmv',
		'it'=>'video/x-ms-wmv',
		'fr'=>'vidéo/x-ms-wmv',
		'tr'=>'video/x-ms-wmv',
	),
	'learner'=>array(
		'en'=>'learner',
		''=>'',
		'es'=>'alumno',
		'el'=>'μαθητή',
		'it'=>'studente',
		'fr'=>'apprenant',
		'tr'=>'Öğrenci',
	),
	'manager'=>array(
		'en'=>'manager',
		''=>'',
		'es'=>'Gerente',
		'el'=>'Διευθυντής',
		'it'=>'Manager',
		'fr'=>'gestionnaire',
		'tr'=>'Yöneticisi',
	),
	'teacher'=>array(
		'en'=>'teacher',
		''=>'',
		'es'=>'Profesor',
		'el'=>'δάσκαλος',
		'it'=>'insegnante',
		'fr'=>'enseignant',
		'tr'=>'öğretmen',
	),
	'counsellor'=>array(
		'en'=>'counsellor',
		''=>'',
		'es'=>'Consejero',
		'el'=>'Σύμβουλος',
		'it'=>'Consigliere',
		'fr'=>'conseiller',
		'tr'=>'danışman',
	),
	'parent'=>array(
		'en'=>'parent',
		''=>'',
		'es'=>'padre',
		'el'=>'γονέας',
		'it'=>'padre',
		'fr'=>'parent',
		'tr'=>'üst',
	),
	'author'=>array(
		'en'=>'author',
		'es'=>'Autor',
		'it'=>'autore',
		'el'=>'συγγραφέας',
	),
	'counselor'=>array(
		'en'=>'counselor',
		'es'=>'Consejero',
		'el'=>'Σύμβουλος',
	),
	'library'=>array(
		'en'=>'library',
		'es'=>'Biblioteca',
		'it'=>'libreria',
		'tr'=>'Kütüphane',
		'el'=>'Βιβλιοθήκη',
	),
	'educational administration'=>array(
		'en'=>'educational administration',
		'es'=>'administración educativa',
		'it'=>'amministrazione educativa',
		'el'=>'διοίκηση της εκπαίδευσης',
	),
	'te'=>array(
		'en'=>'Telugu',
		'es'=>'Telugu',
		'it'=>'Telugu',
		'el'=>'Τελουγκουικά',
	),
	'it'=>array(
		'en'=>'Italian',
		'es'=>'Italiano',
		'it'=>'Italiano',
		'el'=>'Ιταλικά',
	),
	'fi'=>array(
		'en'=>'Finnish',
		'it'=>'Finlandese',
		'es'=>'Finlandés',
		'el'=>'Φινλανδικά',
	),
	'ro'=>array(
		'en'=>'Romanian',
		'it'=>'Rumeno',
		'es'=>'Rumano',
		'el'=>'Ρουμανικά',
	),
	'sv'=>array(
		'en'=>'Swedish',
		'it'=>'Svedese',
		'es'=>'Sueco',
		'el'=>'Σουηδικά',
	),
	'da'=>array(
		'en'=>'Danish',
		'es'=>'Danés',
		'it'=>'Danese',
		'el'=>'Δανικά',
	),
	'nl'=>array(
		'en'=>'Dutch',
		'es'=>'Holandés',
		'it'=>'Olandese',
		'el'=>'Ολλανδικά',
	),
	'ru'=>array(
		'en'=>'Russian',
		'it'=>'Russo',
		'es'=>'Ruso',
		'el'=>'Ρωσικά',
	),
	'application/msword'=>array(
		'en'=>'application/msword',
		'es'=>'application/msword',
		'it'=>'application/msword',
		'el'=>'εφαρμογή/msword',
	),
	'xml'=>array(
		'en'=>'XML',
		'es'=>'XML',
		'it'=>'XML',
		'el'=>'XML',
	),
	'video/mpeg'=>array(
		'en'=>'video/mpeg',
		'it'=>'video/mpeg',
		'es'=>'video/mpeg',
		'el'=>'βίντεο/mpeg',
	),
	'application/x-shockwave-flash'=>array(
		'en'=>'application/x-shockwave-flash',
		'it'=>'Application/x-shockwave-flash',
		'es'=>'application/x-shockwave-flash',
		'el'=>'εφαρμογή/x-shockwave-φλας',
	),
	'application/vnd.ms-word'=>array(
		'en'=>'application/vnd.ms-word',
		'es'=>'aplicación/vnd.ms-palabra',
		'el'=>'εφαρμογή/vnd.ms-λέξη',
	),
	'video/mp4'=>array(
		'en'=>'video/mp4',
		'es'=>'video/mp4',
		'el'=>'βίντεο/mp4',
	),
	'tw'=>array(
		'es'=>'Twi',
		'en'=>'Twi',
		'el'=>'Twi',
	),
	'tr'=>array(
		'it'=>'Turco',
		'es'=>'Turco',
		'en'=>'Turkish',
		'el'=>'Τουρκικά',
	),
	'pl'=>array(
		'en'=>'Polish',
		'es'=>'Polaco',
		'el'=>'Πολωνικά',
	),
	'cs'=>array(
		'en'=>'Czech',
		'es'=>'Checo',
		'el'=>'Τσεχικά',
	),
	'sk'=>array(
		'en'=>'Slovak',
		'es'=>'Eslovaco',
		'el'=>'Σλοβακικά',
	),
	'no'=>array(
		'en'=>'Norwegian',
		'es'=>'Noruego',
		'el'=>'Νορβηγικά',
	),
	'ja'=>array(
		'en'=>'Japanese (ja)',
		'es'=>'Japonés (ja)',
		'el'=>'Ιαπωνικά (ja)',
	),
	'audio/mp3'=>array(
		'en'=>'audio/mp3',
		'es'=>'audio/mp3',
		'el'=>'ήχου/mp3',
	),
	'application/vnd.ms-excel'=>array(
		'en'=>'application/vnd.ms-excel',
		'es'=>'aplicación/vnd.ms-excel',
		'el'=>'εφαρμογή/vnd.ms-excel',
	),
	'video/quicktime'=>array(
		'en'=>'video/quicktime',
		'es'=>'video/quicktime',
		'el'=>'βίντεο/quicktime',
	),
	'cy'=>array(
		'en'=>'Welsh',
		'el'=>'Ουαλλικά',
	),
	'ar'=>array(
		'en'=>'Arabic',
	),
	'zh'=>array(
		'en'=>'Chinese',
		'el'=>'Κινεζικά',
	),
	'video/avi'=>array(
		'en'=>'video/avi',
		'es'=>'video/avi',
		'el'=>'βίντεο/avi',
	),
	'audio/mpeg'=>array(
		'en'=>'audio/mpeg',
		'el'=>'ήχου/mpeg',
	),
	'image/png'=>array(
		'en'=>'image/png',
		'el'=>'image/png',
	),

);